# Generated by Django 4.2.17 on 2025-02-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropboxapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dropboxaccesstokens",
            name="expires_in",
            field=models.DecimalField(null=True, decimal_places=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="dropboxaccesstokens",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="dropboxaccesstokens",
            name="token_type",
            field=models.CharField(default="Bearer", max_length=50),
        ),
    ]
