# Generated by Django 4.2.17 on 2025-02-21 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dropboxapi", "0002_dropboxaccesstokens_expires_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dropboxaccesstokens",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
