# Generated by Django 4.2.17 on 2025-02-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropboxapi", "0003_dropboxaccesstokens_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dropboxaccesstokens",
            name="refresh_token",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="dropboxaccesstokens",
            name="token",
            field=models.CharField(max_length=500),
        ),
    ]
