# Generated by Django 4.2.17 on 2025-02-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropboxapi", "0004_alter_dropboxaccesstokens_refresh_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dropboxaccesstokens",
            name="expires_in",
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
    ]
