# Generated by Django 4.2.17 on 2025-02-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropboxapi", "0005_alter_dropboxaccesstokens_expires_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dropboxaccesstokens",
            name="expires_in",
            field=models.CharField(null=True),
        ),
    ]
