# Generated by Django 4.2.17 on 2025-02-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropboxapi", "0006_alter_dropboxaccesstokens_expires_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dropboxaccesstokens",
            name="expires_in",
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="dropboxaccesstokens",
            name="token",
            field=models.TextField(),
        ),
    ]
