# Generated by Django 4.2.17 on 2025-02-21 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_alter_receipt_expense'),
        ('dropboxapi', '0008_dropboxreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropboxreceipt',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropbox_receipts', to='expenses.expense'),
        ),
    ]
