# Generated by Django 4.2.17 on 2025-02-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dropboxapi", "0009_dropboxreceipt_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="dropboxaccesstokens",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
