# Generated by Django 4.2.17 on 2025-02-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropboxapi', '0010_dropboxaccesstokens_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropboxreceipt',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='dropboxreceipt',
            name='user',
        ),
    ]
